version: '3'

services:
  postgres:
    image: 'bitnami/postgresql'
    restart: always
    ports:
      - '5500:5500'
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=mydb

